---
# role: ansible-role-baseline
# file: .travis.yml

language: python

python:
  - "3.9"

services: docker

env:
  global:
    - TOX_PARALLEL_NO_SPINNER=1

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install tox-travis

script:
  - tox -p 3 -o true

