---
# role: ansible-role-baseline
# file: .travis.yml

language: python

python:
  - "3.8"

services:
  - docker

env:
  - MOLECULE_DIST="jam82/molecule-alpine:3.12"
  - MOLECULE_DIST="jam82/molecule-amazonlinux:latest"
  - MOLECULE_DIST="jam82/molecule-archlinux:latest"
  - MOLECULE_DIST="jam82/molecule-centos:7"
  - MOLECULE_DIST="jam82/molecule-centos:8"
  - MOLECULE_DIST="jam82/molecule-debian:9"
  - MOLECULE_DIST="jam82/molecule-debian:10"
  - MOLECULE_DIST="jam82/molecule-fedora:33"
  - MOLECULE_DIST="jam82/molecule-opensuse:15"
  - MOLECULE_DIST="jam82/molecule-opensuse:tumbleweed"
  - MOLECULE_DIST="jam82/molecule-oraclelinux:7"
  - MOLECULE_DIST="jam82/molecule-oraclelinux:8"
  - MOLECULE_DIST="jam82/molecule-ubuntu:18.04"
  - MOLECULE_DIST="jam82/molecule-ubuntu:20.04"

install:
  - pip install ansible ansible-lint docker molecule molecule-docker yamllint

script:
  - molecule --version
  - ansible --version
  - molecule test
