---
# role: ansible-role-baseline
# file: molecule/resources/playbooks/converge.yml

- name: Converge
  hosts: all
  become: true
  gather_facts: false
  roles:
    # if you want to enable requirements put them in requirements.yml
    # and add here
    # - role: common
    - role: ansible-role-baseline
