---
# role: ansible-role-baseline
# file: molecule/resources/playbooks/converge.yml

- name: Converge
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Include ansible-role-baseline"
      include_role:
        name: "ansible-role-baseline"
